import fs from "node:fs/promises";
import path from "node:path";
import { readLanguage } from "../localization/store.js";
import type { Manifest } from "../project/manifest.js";
import type { ProjectPaths } from "../project/paths.js";
import { findLanguage } from "../steam/languages.js";
import { steamworksUrls } from "../steam/urls.js";

export interface LanguageBundle {
  language: string;
  shortDescription?: string;
  about?: string;
  achievements: { id: string; name?: string; description?: string }[];
}

/** Resolved text for every language (source + targets). Missing translations are left undefined. */
export async function buildBundles(m: Manifest, paths: ProjectPaths): Promise<LanguageBundle[]> {
  const bundles: LanguageBundle[] = [
    {
      language: m.sourceLanguage,
      shortDescription: m.store.shortDescription || undefined,
      about: m.store.about || undefined,
      achievements: m.achievements.map((a) => ({ id: a.id, name: a.name, description: a.description || undefined })),
    },
  ];
  for (const lang of m.targetLanguages) {
    const t = await readLanguage(paths, lang);
    bundles.push({
      language: lang,
      shortDescription: t["store.shortDescription"],
      about: t["store.about"],
      achievements: m.achievements.map((a) => ({
        id: a.id,
        name: t[`achievements.${a.id}.name`],
        description: t[`achievements.${a.id}.description`],
      })),
    });
  }
  return bundles;
}

function csvCell(s: string | undefined): string {
  const v = s ?? "";
  return /[",\n\r]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v;
}

const yes = (b: boolean) => (b ? "✔" : "—");

/**
 * Writes everything a person or a browser agent needs to finish the job in Steamworks:
 *   store/<lang>.json, achievements_localization.csv and STEAMWORKS_CHECKLIST.md.
 */
export async function exportBundle(m: Manifest, paths: ProjectPaths): Promise<{ files: string[] }> {
  const out = paths.outputDir;
  await fs.mkdir(path.join(out, "store"), { recursive: true });
  const bundles = await buildBundles(m, paths);
  const files: string[] = [];

  for (const b of bundles) {
    const f = path.join(out, "store", `${b.language}.json`);
    await fs.writeFile(f, JSON.stringify(b, null, 2) + "\n", "utf8");
    files.push(f);
  }

  const langs = bundles.map((b) => b.language);
  const rows = [["id", "field", ...langs].join(",")];
  for (const a of m.achievements) {
    for (const field of ["name", "description"] as const) {
      const cells = bundles.map((b) => csvCell(b.achievements.find((x) => x.id === a.id)?.[field]));
      rows.push([a.id, field, ...cells].join(","));
    }
  }
  const csv = path.join(out, "achievements_localization.csv");
  await fs.writeFile(csv, "﻿" + rows.join("\r\n") + "\r\n", "utf8");
  files.push(csv);

  const checklist = path.join(out, "STEAMWORKS_CHECKLIST.md");
  await fs.writeFile(checklist, renderChecklist(m, bundles), "utf8");
  files.push(checklist);
  return { files };
}

function renderChecklist(m: Manifest, bundles: LanguageBundle[]): string {
  const u = m.appId ? steamworksUrls(m.appId) : undefined;
  const link = (label: string, url?: string) => (url ? `[${label}](${url})` : label);
  const L: string[] = [];
  L.push(`# Steamworks checklist — ${m.name}${m.appId ? ` (App ${m.appId})` : ""}`, "");
  L.push("Generated by steamworks-mcp. Values below come from `steamworks.yaml` and `localization/*.yaml`.", "");

  L.push(`## 1. Store page → Description (${link("Edit Store Page", u?.storePage)})`, "");
  L.push("Switch the language drop-down in the top right of each editor, or use the **Localization** tab to import/export.", "");
  for (const b of bundles) {
    const name = findLanguage(b.language)?.name ?? b.language;
    L.push(`- [ ] **${name}** — short description ${b.shortDescription ? "✔" : "**missing**"}, about ${b.about ? "✔" : "**missing**"} (\`store/${b.language}.json\`)`);
  }
  L.push("");

  const langs = Object.entries(m.store.supportedLanguages);
  if (langs.length) {
    L.push("## 2. Store page → Supported languages", "", "| Language | Interface | Full audio | Subtitles |", "|---|---|---|---|");
    for (const [code, s] of langs) L.push(`| ${findLanguage(code)?.name ?? code} | ${yes(s.interface)} | ${yes(s.fullAudio)} | ${yes(s.subtitles)} |`);
    L.push("");
  }

  const req = m.store.systemRequirements;
  const platforms = (["windows", "macos", "linux"] as const).filter((p) => req[p]);
  if (platforms.length) {
    L.push("## 3. Store page → System requirements", "");
    for (const p of platforms) {
      for (const tier of ["minimum", "recommended"] as const) {
        const r = req[p]?.[tier];
        if (!r) continue;
        L.push(`**${p} — ${tier}**`, "");
        for (const [k, v] of Object.entries(r)) if (v) L.push(`- ${k}: ${v}`);
        L.push("");
      }
    }
  }

  if (m.store.tags.length) L.push("## 4. Store page → Tags", "", m.store.tags.map((t) => `\`${t}\``).join(", "), "");

  L.push("## 5. Graphical assets", "", "Upload from `steamworks-out/assets/` (run `assets_generate` first). Screenshots: `" + m.store.screenshotsDir + "`.", "");

  if (m.achievements.length) {
    L.push(`## 6. Achievements (${link("Stats & Achievements", u?.achievements)})`, "");
    L.push("| API name | Name | Description | Hidden | Icons |", "|---|---|---|---|---|");
    for (const a of m.achievements) {
      L.push(`| \`${a.id}\` | ${a.name} | ${a.description} | ${yes(a.hidden)} | \`achievements/${a.id}.jpg\`, \`${a.id}_locked.jpg\` |`);
    }
    L.push("", `Localized names/descriptions: ${link("Achievement Localization", u?.achievementLocalization)} — values in \`achievements_localization.csv\`.`, "");
    L.push("Remember to **Publish** after saving; achievements are not live until published.", "");
  }

  if (m.cloud) {
    L.push(`## 7. Steam Cloud (${link("Steam Cloud settings", u?.cloud)})`, "");
    if (m.cloud.byteQuota !== undefined) L.push(`- Byte quota per user: **${m.cloud.byteQuota}** (${(m.cloud.byteQuota / 1024 / 1024).toFixed(1)} MB)`);
    if (m.cloud.fileQuota !== undefined) L.push(`- Number of files per user: **${m.cloud.fileQuota}**`);
    const roots = m.cloud.autoCloud?.roots ?? [];
    if (roots.length) {
      L.push("", "**Auto-Cloud root paths**", "", "| Root | Subdirectory | Pattern | OS | Recursive |", "|---|---|---|---|---|");
      for (const r of roots) L.push(`| ${r.root} | ${r.subdirectory || "."} | ${r.pattern} | ${r.os} | ${yes(r.recursive)} |`);
    }
    const ov = m.cloud.autoCloud?.rootOverrides ?? [];
    if (ov.length) {
      L.push("", "**Root overrides** (root paths must be set to *All OSes*)", "", "| Original root | OS | New root | Add/Replace path | Replace |", "|---|---|---|---|---|");
      for (const o of ov) L.push(`| ${o.originalRoot} | ${o.os} | ${o.newRoot} | ${o.addOrReplacePath} | ${yes(o.replace)} |`);
    }
    L.push("", "Save, then **Publish** from the Steamworks publish tab.", "");
  }

  if (m.app) {
    L.push(`## 8. Installation → General / Launch options (${link("Installation", u?.installation)})`, "");
    if (m.app.installFolder) L.push(`- Install folder: \`${m.app.installFolder}\``);
    for (const [i, o] of m.app.launchOptions.entries()) {
      L.push(`- Launch option ${i + 1}: \`${o.executable}\`${o.arguments ? ` args \`${o.arguments}\`` : ""} — OS ${o.os}, ${o.arch}-bit${o.description ? ` — "${o.description}"` : ""}${o.betaKey ? ` (beta: ${o.betaKey})` : ""}`);
    }
    L.push("");
  }
  return L.join("\n");
}
