"""The skills in skills/: valid frontmatter, real tools, real steamworks.yaml fields, real skill references."""

from __future__ import annotations

import re
from pathlib import Path

import anyio
import pytest
from mcp import Client
from ruamel.yaml import YAML

from steamworks_mcp.config import Config
from steamworks_mcp.manifest import paths as fp
from steamworks_mcp.server import create_server
from steamworks_mcp.validate.code import rules_file

ROOT = Path(__file__).resolve().parents[1]
SKILLS = sorted(p for p in (ROOT / "skills").iterdir() if p.is_dir())
NAME = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
FIELD_ROOTS = (
    "game",
    "store",
    "apps",
    "pricing",
    "release",
    "content",
    "assets",
    "achievements",
    "stats",
    "leaderboards",
    "prerequisites",
)
FIELD = re.compile(r"`((?:" + "|".join(FIELD_ROOTS) + r")\.[A-Za-z0-9_.<>*-]+)`")


def tools() -> set[str]:
    async def names() -> set[str]:
        async with Client(create_server(Config(workspace_root=ROOT, browser_enabled=True))) as client:
            return {t.name for t in (await client.list_tools()).tools}

    return anyio.run(names)


TOOLS = tools()


def split(skill: Path) -> tuple[dict[str, str], str]:
    text = (skill / "SKILL.md").read_text(encoding="utf-8")
    assert text.startswith("---\n"), skill.name
    head, body = text[4:].split("\n---\n", 1)
    return dict(YAML(typ="safe").load(head)), body


def test_there_are_many_skills() -> None:
    assert len(SKILLS) >= 30


@pytest.mark.parametrize("skill", SKILLS, ids=lambda p: p.name)
def test_frontmatter(skill: Path) -> None:
    meta, body = split(skill)
    assert meta["name"] == skill.name and skill.name.startswith("steamworks-")
    assert NAME.match(meta["name"]) and len(meta["name"]) <= 64
    assert 40 <= len(meta["description"]) <= 1024
    assert body.strip()


@pytest.mark.parametrize("skill", SKILLS, ids=lambda p: p.name)
def test_named_tools_exist(skill: Path) -> None:
    _, body = split(skill)
    listed = re.search(r"^Tools: (.+)$", body, re.M)
    if listed is None:  # generated from a prompt: every call it makes is checked by test_data
        assert "Generated by scripts/gen_skills.py" in body
        return
    names = re.findall(r"`([a-z_]+)`", listed.group(1))
    assert names and not [n for n in names if n not in TOOLS], [n for n in names if n not in TOOLS]
    called = set(re.findall(r"`([a-z_]+)\(", body))
    assert not {c for c in called if c not in TOOLS}, sorted(c for c in called if c not in TOOLS)
    assert not {c for c in called if c not in names}, "call a tool that the Tools line does not list"


@pytest.mark.parametrize("skill", SKILLS, ids=lambda p: p.name)
def test_field_paths_are_real(skill: Path) -> None:
    _, body = split(skill)
    bad = []
    for path in FIELD.findall(body):
        concrete = (
            path.replace("<app>", "main")
            .replace("<n>", "0")
            .replace("<id>", "ACH_X")
            .replace("<name>", "BOARD")
            .replace("<language>", "german")
            .rstrip(".*")
        )
        if not fp.is_valid(concrete) and not fp.is_valid(concrete.rsplit(".", 1)[0]):
            bad.append(path)
    assert not bad, bad


@pytest.mark.parametrize("skill", SKILLS, ids=lambda p: p.name)
def test_skill_references_exist(skill: Path) -> None:
    _, body = split(skill)
    names = {p.name for p in SKILLS}
    referenced = set(re.findall(r"`(steamworks-[a-z-]+)`", body)) - {"steamworks-mcp"}
    groups = {g.id for g in rules_file().groups}  # check_code's rule groups
    assert not referenced - names - groups, sorted(referenced - names - groups)
