"""Regenerate skills/: the server's MCP prompts as skills, for clients that do not show MCP prompts.

uv run python scripts/gen_skills.py          # write
uv run python scripts/gen_skills.py --check  # exit 1 if anything is out of date (used by the tests)

Each prompt becomes skills/<skill>/SKILL.md, its text taken from the running server so the two never drift apart.
A prompt with a hand-written skill (HANDWRITTEN) is skipped; the tests check that skill still names every tool the
prompt does. Copy the folders to ~/.claude/skills/ for Claude Code.
"""

from __future__ import annotations

import re
import sys
import tempfile
from pathlib import Path

import anyio
from mcp import Client

from steamworks_mcp.config import Config
from steamworks_mcp.server import create_server

ROOT = Path(__file__).resolve().parents[1]
SKILLS = ROOT / "skills"
NAMES = {
    "release_assistant": "steamworks-release",
    "market_research": "steamworks-market-research",
    "write_store_page": "steamworks-store-page",
    "localize_everything": "steamworks-localize",
    "design_achievements": "steamworks-achievements",
    "review_gate": "steamworks-review-gate",
}
"""Prompt name -> skill name. Every prompt needs one (the tests check it)."""
HANDWRITTEN = {"write_store_page"}
"""Prompts whose skill is written by hand (a longer workflow than the prompt)."""
ARGUMENTS = {
    "path": "the game's folder, the one with steamworks.yaml (relative to the server's workspace root)",
    "gate": "the release gate: 0 prerequisites, 1 store page, 2 build review, 3 release",
}


async def prompts() -> list[tuple[str, str, str, list[str], str]]:
    """(name, title, description, argument names, text with <argument> placeholders) of every server prompt."""
    out = []
    with tempfile.TemporaryDirectory() as tmp:
        async with Client(create_server(Config(workspace_root=Path(tmp)))) as client:
            for p in (await client.list_prompts()).prompts:
                args = [a.name for a in p.arguments or []]
                msg = await client.get_prompt(p.name, {a: f"<{a}>" for a in args})
                text = msg.messages[0].content.text  # type: ignore[union-attr]
                out.append((p.name, p.title or p.name, p.description or "", args, text))
    return out


def render(name: str, title: str, description: str, args: list[str], text: str) -> str:
    unknown = [a for a in args if a not in ARGUMENTS]
    if unknown:
        raise SystemExit(f"{name}: describe the argument(s) {', '.join(unknown)} in ARGUMENTS")
    arg_lines = "\n".join(f"- `<{a}>`: {ARGUMENTS[a]}" for a in args)
    desc = re.sub(r"\s+", " ", description).strip()
    return (
        "---\n"
        f"name: {NAMES[name]}\n"
        f"description: {desc} Uses the steamworks-mcp server's tools; use it when the user asks for this and the "
        "server is connected.\n"
        "---\n\n"
        f"<!-- Generated by scripts/gen_skills.py from the server's `{name}` prompt. Do not edit by hand. -->\n\n"
        f"# {title}\n\n"
        "Arguments, from what the user wrote after the command (ask for any that are missing):\n\n"
        f"{arg_lines}\n\n"
        f"{text.strip()}\n\n"
        "Never claim something was done in Steamworks unless a tool reported it as applied, never approve values "
        "without the user's agreement, and never publish: the user publishes in Steamworks.\n"
    )


def outputs() -> dict[Path, str]:
    found = anyio.run(prompts)
    missing = sorted({n for n, *_ in found} - set(NAMES))
    if missing:
        raise SystemExit(f"no skill name for the prompt(s) {', '.join(missing)}: add them to NAMES")
    return {
        SKILLS / NAMES[name] / "SKILL.md": render(name, title, desc, args, text)
        for name, title, desc, args, text in found
        if name not in HANDWRITTEN
    }


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for path, text in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(ROOT).as_posix()}")
    if stale:
        print("out of date (run: uv run python scripts/gen_skills.py):", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
