"""Regenerate rules/: Cursor rules (.mdc) from the server's code rules (src/steamworks_mcp/data/code_rules.yaml).

uv run python scripts/gen_rules.py          # write
uv run python scripts/gen_rules.py --check  # exit 1 if anything is out of date (used by the tests)

One file per group, so Cursor shows the advice while the matching files are edited. check_code runs the same rules
over the whole project with file and line.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from steamworks_mcp.validate.code import rules_file

ROOT = Path(__file__).resolve().parents[1]
RULES = ROOT / "rules"


def render(group_id: str) -> str:
    data = rules_file()
    group = next(g for g in data.groups if g.id == group_id)
    globs = "\n".join(f'  - "{g}"' for g in group.globs)
    lines = [
        "---",
        f"description: {json.dumps(f'Steamworks - {group.title}. {group.guidance}', ensure_ascii=False)}",
        "alwaysApply: false",
        "globs:",
        globs,
        "---",
        "",
        "<!-- Generated by scripts/gen_rules.py from src/steamworks_mcp/data/code_rules.yaml. Do not edit by hand. -->",
        "",
        f"# Steamworks: {group.title}",
        "",
        group.guidance,
        "",
    ]
    for r in (r for r in data.rules if r.group == group_id):
        lines += [
            f"## {r.title} ({r.severity})",
            "",
            f"- Why: {' '.join(r.why.split())}",
            f"- Fix: {' '.join(r.fix.split())}",
            f"- Source: {r.source}",
            "",
        ]
    lines += [
        "With the steamworks-mcp server connected, `check_code(path)` finds these problems in the whole project, with "
        f'file and line (`check_code(path, rules=["{group_id}"])` for this group only).',
        "",
    ]
    return "\n".join(lines)


def outputs() -> dict[Path, str]:
    return {RULES / f"{g.id}.mdc": render(g.id) for g in rules_file().groups}


def main() -> int:
    check = "--check" in sys.argv
    wanted = outputs()
    stale = []
    for path, text in wanted.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
            print(f"wrote {path.relative_to(ROOT).as_posix()}")
    extra = sorted(p.relative_to(ROOT).as_posix() for p in RULES.glob("*.mdc") if p not in wanted)
    if extra:
        if check:
            stale += extra
        else:
            for rel in extra:
                (ROOT / rel).unlink()
                print(f"removed {rel}")
    if stale:
        print("out of date (run: uv run python scripts/gen_rules.py):", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
